# Generated by Django 5.2.1 on 2025-05-11 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_client_car_reg_alter_client_email_alter_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='car_reg',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.client'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='service',
            field=models.CharField(max_length=200),
        ),
    ]
