# Generated by Django 5.2.1 on 2025-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_remove_client_car_reg_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='car_reg',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
