# Generated by Django 5.2.1 on 2025-05-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
