# Generated by Django 5.2.1 on 2025-05-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_quote_car_alter_quote_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='car_reg',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
