# Generated by Django 5.2.1 on 2025-05-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_quote_car_reg'),
    ]

    operations = [
    ]
