# Generated by Django 5.2.1 on 2025-05-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_auto_20250511_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='car_reg',
        ),
    ]
